### ISSUE TITLE
Refactor Dashboard to implement good practice for React

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/web-mdm-dashboard#367]
Complete the task to create a good practice for React
# Diagram of Architecture:

![architecture_react](https://user-images.githubusercontent.com/12489333/36646116-93f16748-1a49-11e8-8ffe-6f075297eecc.jpg)

# ApplicationWebDashboard Code Prototype
![seleccion_107](https://user-images.githubusercontent.com/12489333/36646300-4b404aac-1a4c-11e8-9253-a1dcfc5548b9.png)

# CSS:

- [x] Create new file structure to management css styles with a adaptation of Inverted Triangle CSS
- [x] separate elements of each UI component into different files with the same component name
- [x] Use [BEM](http://getbem.com/naming/) to name classes
- [x] Delete useles CSS files

# React

### Task: Create asynchronus components:

> The asynchronous components help to minimize the size of the main package of the application and are imported dynamically when necessary.

- [x] Create Async Containers:
    - [x] Admin Dashboard
    - [x] SignUp
    - [x] ForgotPassword
    - [x] ValidateAccount (Non-Reusable Component)
    - [x] Logout (Non-Reusable Component)

### Task: File structure for Redux 
> https://redux.js.org/faq/code-structure

- [x] Separate reducers in different folders that contain:
    - actions creators
    - initial state
    - action types 
    - reducer
- [x] Implement Redux to management the global state of 
    - [x] I18N
    - [x] SignIn
    - [x] SignUp
    - [x] UI (Loading Spinners, Notifications)

### Task Change File Structure:
- [x] Remane `Utils/` folder to `shared/` 
- [x] Create `applications/` folder (Why?: Look the Diagram)
- [x] Create and Implement `HOC` Layout for AdminDashboard Container (Navbar & Right Menu)
- [x] Implement `HOC` I18N
- [x] Implement routers to Device, Fleets, etc
- [x] Rename folder with conventionals name (`assets/`, `containers/`, `components/`,` hoc/`)
- [x] Change class components without state to stateless function 
- [x] Create `Logout`  Non-reusable component

### Task Optimize Rendering and Bundle

- [x]  Implement `PureComponent`
- [ ] Improve the  React Component Lifecycle
- [x] Remove useless npm dependencies

#### References

#369
#390
https://github.com/flyve-mdm/web-mdm-dashboard/pull/781

**Comment by rafaelje** [comment]
@CharlyJazz do you have a proposal to keep organized the project structure that we talk now with Redux, please share with us

**Comment by CharlyJazz** [comment]
https://redux.js.org/faq/code-structure
https://marmelab.com/blog/2015/12/17/react-directory-structure.html
https://medium.com/@msandin/strategies-for-organizing-code-2c9d690b6f33

Example:
![image](https://user-images.githubusercontent.com/12489333/36644622-3a3003ec-1a33-11e8-9976-6930836caac4.png)
